---
- name: Copy the nginx conf
  copy:
    src: nginx
    dest: "{{ docker_project_path }}"
- name: Copy the Dockerfile for nginx
  copy:
    src: Dockerfile.nginx
    dest: "{{ docker_project_path }}"
- name: Build the container image for nginx
  command: docker build -t "{{ docker_image_name }}" -f "{{ docker_project_path }}"/Dockerfile.nginx "{{ docker_project_path }}"
- name: Tag the image with the repositoryUri from AWS ECR
  command: docker tag "{{ docker_image_name }}" "{{ ecr.repositoryUri }}"
