---
- hosts: all
  become: yes

  vars_files:
    - group_vars/main.yml

  tasks:
    - include_role:
        name: ecs
      when: app_env == "production"
    - include_role:
        name: dogbuddyapp # this role expects variable app_env to be defined; we will do this with -e 'app_env=development' or -e 'app_env=production', when executing this playbook with ansible-playbook command
    - include_role:
        name: nginx
      when: app_env == "production"
    - name: Deploy the container
      command: docker-compose -f "{{ docker_project_path }}/docker-compose.yml" up -d
      when: app_env == "development"
