---
- name: Create directory for docker files and container data
  file:
    path: "{{ docker_project_path }}"
    state: directory
- name: Copy the Dockerfile for web app
  template:
    src: "{{ web_dockerfile }}"
    dest: "{{ docker_project_path }}/Dockerfile.web"
- name: Copy the docker-compose.yml file
  copy:
    src: "docker-compose.yml"
    dest: "{{ docker_project_path }}"
- name: Copy the "{{ app_root }}" directory
  copy:
    src: "{{ app_root }}"
    dest: "{{ docker_project_path }}"

- name: Build the container image for web app
  command: docker build -t "{{ docker_image_name }}" -f "{{ docker_project_path }}"/Dockerfile.web "{{ docker_project_path }}"
- name: Tag the image with the repositoryUri from AWS ECR
  command: docker tag "{{ docker_image_name }}" "{{ ecr_repositoryUri }}"
  when: app_env == "production"
- name: Push the image with to AWS ECR
  command: docker push "{{ ecr_repositoryUri }}"
  when: app_env == "production"
