---
- local_action: stat path=/Applications/Docker.app
  register: app_exists

# - command: mkdir -p ./tmp/
#   when: app_exists.stat.exists == False

- file:
    path: ./tmp/
    state: directory
  when: app_exists.stat.exists == False

- get_url:
    url: https://download.docker.com/mac/stable/Docker.dmg
    dest: ./tmp/Docker.dmg
  when: app_exists.stat.exists == False

- command: hdiutil attach ./tmp/Docker.dmg -nobrowse -mountpoint ./tmp/Docker
  when: app_exists.stat.exists == False

- shell: cp -aR ./tmp/Docker/*.app /Applications/Docker.app
  when: app_exists.stat.exists == False

- command: hdiutil detach ./tmp/Docker/
  when: app_exists.stat.exists == False

- command: rm -R ./tmp/
  when: app_exists.stat.exists == False

- name: Start docker daemon
  command: open --background -a Docker
