FROM ubuntu:16.04

ENV FLASK_APP=app.py
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV APP_ENV="{{ app_env }}"

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip

COPY ./web /web/

WORKDIR /web
RUN pip3 install -r requirements.txt

CMD flask run --host=0.0.0.0
